export const constants = {
    CLI_PREFIX: "m365",
    ACTION_APP_FILE_PATH: "APP_FILE_PATH",
    ACTION_SCOPE: "SCOPE",
    ACTION_SITE_COLLECTION_URL: "SITE_COLLECTION_URL",
    ACTION_SKIP_FEATURE_DEPLOYMENT: "SKIP_FEATURE_DEPLOYMENT",
    ACTION_OVERWRITE: "OVERWRITE"
};